### ISSUE TITLE
Katacoda shutdown

### ISSUE THREAD

**Issue by Maxim-Filimonov** [pactflow/docs.pactflow.io#120]
Reading [this tutorial](https://docs.pactflow.io/docs/workshops/bi-directional-contract-testing)
I wanted to try to follow it on Katacoda, and apparently it has been [shutdown](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html) about a week ago.

> As a result, we can no longer support katacoda.com for public use, and we’ll be shuttering the site on June 15, 2022.

**Comment by YOU54F** [comment]
Hey,

I know right, totally sucks. Thanks for letting us know

We’ve moved it over to killercoda

https://killercoda.com/pactflow

but is still a WIP at the moment, there are a couple of niggles.

happy for you to try it out and pass any feedback.

**Comment by Maxim-Filimonov** [comment]
@YOU54F just tried pactflow-nodejs and got stuck instantly on the step 2 :\ 
I cannot see `copy to editor` command anywhere on the screen. Is it present in killercoda?

**Comment by YOU54F** [comment]
It’s currently a wip, no copy to editor in killercoda so needs to be echoed to the terminal into a file.

the can I deploy js currently has that in place, but the instructions will also need tweaking.

The bi directional one should be good, bar some formatting and order of installing the pre reqs ( node / npm / jq and Java on the Java course )

**Comment by YOU54F** [comment]
Hey @Maxim-Filimonov

We have removed the links for now, and will get the update finished soon and back up.

I loved the katacoda, and there is value is writing something up about the transition, as it may help others who are stuck in the same situation. Props to the killercoda team!
