### ISSUE TITLE
make test_webhook command in ci/cd workshop doesn't exist in the MakeFile

### ISSUE THREAD

**Issue by lucasfvera** [pactflow/docs.pactflow.io#221]
I'm trying to follow the CI/CD Workshop for PactFlow and I got stuck in the "[Implementing the Provider Changes](https://docs.pactflow.io/docs/workshops/ci-cd/workshop/implementing-the-provider-changes)" part.

Step 4 says:

> 4. Run PACT_URL=<PACT URL HERE> make test_webhook. This test should correctly fail with the error Could not find key "color" in the output.

But it seems there is no such command.

**Comment by YOU54F** [comment]
https://github.com/pactflow/example-provider/blob/594529a11b188f55d6dc86d95355f8a947d357b3/Makefile#L98

try this

**Comment by YOU54F** [comment]
or make ci_webhook which is used in the ci run as the command above is just for manually testing the created webhook

https://github.com/pactflow/example-provider/blob/594529a11b188f55d6dc86d95355f8a947d357b3/.github/workflows/contract_requiring_verification_published.yml#L44

**Comment by YOU54F** [comment]
sorry didn’t mean to close!

**Comment by lucasfvera** [comment]
Thanks for getting back to me so fast!
The first one `PACT_URL=**** make test_contract_requiring_verification_published_webhook` didn't work. It said invalid URL or something like that.
The second one `PACT_URL=**** make ci_webhook` failed as expected.
Then I was able to follow the next steps and make the tests pass.

Maybe you can update the docs to use the command
`PACT_URL=**** make ci_webhook`
and also change the file name with the state changes to `src/product/pact.setup.js`

**Comment by YOU54F** [comment]
agreed, apologies these slipped the net in my rewrite of the new guide. 

happy to accept an pr updates if you are able to update with the correct steps? there will be an edit this page link at the bottom of all our docs
