### ISSUE TITLE
docker pactfoundation/pact-cli is not compatible with arm64

### ISSUE THREAD

**Issue by gergo83** [pactflow/docs.pactflow.io#227]
Hi Team,

Thank you very much for this great product. It helps a lot to my company.

I'm using a M1 mac book and tried to run the latest `pactfoundation/pact-cli` image on my local machine to verify some pacts, but unfortunately the image is not supported on my architecture.

Can you please release it to ARM64 architecture?

Thank you,
Gergo

**Comment by YOU54F** [comment]
This isn't the correct place to raise this, it would be the pact-ruby-cli

https://github.com/pact-foundation/pact-ruby-cli

you can run it today, by setting your `DOCKER_DEFAULT_PLATFORM=linux/amd64` and running it with emulation

**Comment by gergo83** [comment]
Thank you
