### ISSUE TITLE
snag: doc sync failing since org setup with sso

### ISSUE THREAD

**Issue by YOU54F** [pactflow/docs.pactflow.io#291]
Issue 1 : PAT tokens require SSO 

From triggering job

https://github.com/pactflow/example-provider-dotnet/actions/runs/9223404200/job/25376545105

```
{
  "message": "Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.",
  "documentation_url": "https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"
}
```

Issue 2: Main branch in docs is now write-protected, and as such the docs sync fails, as it attempts to write to master.

https://github.com/pactflow/docs.pactflow.io/actions/runs/9223601246/job/25377172271

```
Error: Error: To https://github.com/pactflow/docs.pactflow.io
!	refs/heads/master:refs/heads/master	[remote rejected] (protected branch hook declined)
Done
Pushing to https://github.com/pactflow/docs.pactflow.io
POST git-receive-pack (1007 bytes)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Changes must be made through a pull request.        
error: failed to push some refs to 'https://github.com/pactflow/docs.pactflow.io'
```

Need to relax for this job, or have this job write to a new branch and open a PR

**Comment by YOU54F** [comment]
To fix issue 2, raise PR on new branch after doc sync

https://github.com/pactflow/docs.pactflow.io/pull/292

manually triggered doc sync for event all-docs-updated against the above branch

https://github.com/pactflow/docs.pactflow.io/tree/all-docs-updated

PR with updated docs

https://github.com/pactflow/docs.pactflow.io/pull/293

**Comment by JP-Ellis** [comment]
I see the two linked issues have been merged, I think this issue can be closed?

**Comment by YOU54F** [comment]
yep yep
