### ISSUE TITLE
Update CI/CD workshop

### ISSUE THREAD

**Issue by bethesque** [pactflow/docs.pactflow.io#38]
* The workshop is unnecessarily confusing because it compares the with pending/without pending and with WIP/without WIP flows. Now that these are standard features, we should just teach people how to coordinate the implementation of new features with Pact, assuming they are enabled.
* It needs to be renamed from "CI/CD workshop" to something like "Pact feature workflow workshop" (except, better), as it's really about how to get new features out rather than the full CI/CD set up (it doesn't cover can-i-deploy in any depth  as there's another workshop for that).

**Comment by YOU54F** [comment]
Hopefully addressed in #149

If anyone gets stuck, please raise a new issue, or get in touch if you want to help build out a workshop
